### ISSUE TITLE
Tau Killteam points error

### ISSUE THREAD

**Issue by Malignence** [BSData/wh40k-shadow-war-armageddon#11]
Hey guys, thanks for the awesome data file, just wanted to point out you show the recon drone and grav inhibitor drone as 0 points when they're 110 and 50. Thanks!

**Comment by Crothas** [comment]
@Malignence This has been fixed already https://github.com/BSData/wh40k-shadow-war-armageddon/commit/ac5fd8b1fa4625ce375b445b7789c559e8c5b9e0
This will be in the new release.
