### ISSUE TITLE
[Anon] Bug report: Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-shadow-war-armageddon#31]
**File:** Craftworlds.catz

**BattleScribe version:** 2.00.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Guardian Gunners need access to platforms. Currently can only take catapult.

**Comment by GenWilhelm** [comment]
Platforms are available separately under 'Uncategorised', since they are only assigned to a gunner at the start of a game.
