### ISSUE TITLE
Ork Boyz.catz

### ISSUE THREAD

**Issue by Saxman-Steph** [BSData/wh40k-shadow-war-armageddon#32]
Ork Boyz kill team requires clan.

No option to select one.

**Comment by cartag** [comment]
Is there a skill tree for no clan Orks?

**Comment by cartag** [comment]
Wow I need to learn to read

**Comment by Wurrkop** [comment]
Ork Yoofs should have 1 wounds rather than 2 as currently is in the file.

**Comment by Crothas** [comment]
Will fix this when I get off work.

**Comment by Crothas** [comment]
@Saxman-Steph The option to select the clan is available in the uncategorised selection
