### ISSUE TITLE
[Join Request] Matt

### ISSUE THREAD

**Issue by buggritt** [BSData/wh40k-shadow-war-armageddon#45]
I just left a bug report about red dot sights and Orks when it occured to me that I could do that myself. Then it occured to me that I could fix other bugs and work on updates/improvements. Then I got excited and ended up here.

Please add me in, I use battlescribe a lot and it would be awesome to give something back.

**Comment by amis92** [comment]
Hello, @buggritt. Welcome aboard! (Invitation: https://github.com/BSData/wh40k-shadow-war-armageddon/invitations)

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
