### ISSUE TITLE
Promethium Cache tracking

### ISSUE THREAD

**Issue by darkestvisions** [BSData/wh40k-shadow-war-armageddon#46]
I really like how I can track Advances for my fighters - I wonder if there is also a way to track promethium caches for a force, so I can work through a campaign?

**Comment by Crothas** [comment]
We are working on Advancements currently, and we will work on a promethium cache tracking system as well.

**Comment by david-jobling** [comment]
Suggest it's possible to track "new recruit" missions completed and also "miss a mission" 

There is also a result where the model can gain frenzy but misses a mission.

**Comment by Wurrkop** [comment]
If you have the paid version of battlescribe you can add notes, my group uses that feature to track caches.
