### ISSUE TITLE
[Anon] Bug report: Tau Pathfinder.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-shadow-war-armageddon#5]
**File:** Tau Pathfinder.catz

**BattleScribe version:** 2.00.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** For the Tau Kill team. The point cost for the Recon drone and the Grav drone is stated as No cost. It should be 110 points and 50 points respectively. Thank you.

**Comment by Crothas** [comment]
Thank, will get this fixed ASAP.

**Comment by Crothas** [comment]
https://github.com/BSData/wh40k-shadow-war-armageddon/commit/ac5fd8b1fa4625ce375b445b7789c559e8c5b9e0 
Got it fixed. Will be in the next release, which will be hopefully later today.
