### ISSUE TITLE
SM Scouts Telescopic sights needed for bolt pistols

### ISSUE THREAD

**Issue by Glaidr** [BSData/wh40k-shadow-war-armageddon#57]
Hey guys. 

Before i say anything you guys are doing amazing. Getting annoyed on your behalf at the numptys on FB. Thanks for the work and keep it up! 

When you get to it, Telescopic sights are missing on bolt pistols (and maybe others?) they are available for everything but shotguns as per rule book.

**Comment by GenWilhelm** [comment]
Rule book says "A telescopic sight may be fitted to a basic weapon or a special weapon." No mention of pistols, unless it's a specific space marines rule?

**Comment by Glaidr** [comment]
Huh. You know what I'll have to check that. I just assumed cause all the Scout pistols have sights...

**Comment by Crothas** [comment]
Only Red Dot Laser Sights can be attached to pistols.
