### ISSUE TITLE
[Anon] Bug report: Tau Pathfinder.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-shadow-war-armageddon#63]
**File:** Tau Pathfinder.catz

**BattleScribe version:** 2.00.15

**Platform:** Windows

**Dropbox:** No

**Description:** Tau Pathfinder Kill Team displays no entries (in the available entries menu), when selected, Other teams display as normal.

**Comment by GenWilhelm** [comment]
Tau have a different Force Org due to their unique drone category. You just need to select "Tau Kill Team" instead of "Kill Team" from the second selection box when adding a new force.
