### ISSUE TITLE
[Anon] Bug report: Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-shadow-war-armageddon#68]
**File:** Genestealer Cults.catz

**BattleScribe version:** 2.00.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Grenade launcher does not include option for Krak grenades.

**Comment by GenWilhelm** [comment]
The options for ammunition are under the weapon entry. In general, any entry with an orange 'pip' on the left side has additional options when you tap on it.

![gc](https://cloud.githubusercontent.com/assets/22036809/25956394/8496ba70-3663-11e7-941d-8075f6a69e67.png)

**Comment by joeyb78** [comment]
I can see the ammo option, but clicking grenade launcher on the iPhone version only opens up frag and weapon reload, no krak option.

**Comment by GenWilhelm** [comment]
Tap the radio button on the right-hand side of the Frag Grenades selection.

**Comment by joeyb78** [comment]
Oh, the button!  Sorry, thanks!
