### ISSUE TITLE
[Anon] Bug report: Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-shadow-war-armageddon#71]
**File:** Genestealer Cults.catz

**BattleScribe version:** 2.00.17

**Platform:** Windows

**Dropbox:** No

**Description:** Validation Error for using 3 Specialists. Genestealer Cults specifically lists that they can take up to 3 Specialists rather than the usual 2.

**Comment by GenWilhelm** [comment]
When starting your roster select "Genestealer Cult Hybrid Kill Team" from the second drop down, rather than the default "Kill Team".
