### ISSUE TITLE
Special Weapons

### ISSUE THREAD

**Issue by Jhuldan** [BSData/wh40k-shadow-war-armageddon#72]
The Chaos Space Marine gunner is supposed to have access to the special Weapons: Flamer, plasma gun, and Melta Gun. Please add these into the options for the Chair Space Marine Gunner.

**Comment by GenWilhelm** [comment]
Special Weapons are available at the bottom of the options for the Chaos Gunner, beneath Skills.

![chaos gunner](https://cloud.githubusercontent.com/assets/22036809/26445054/91818322-4136-11e7-8268-149971770a4b.png)
